name: Python Extractor CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Faz cache do requirements.txt para rodar super rápido

      - name: Instalar Dependências e Validar
        # Roda direto na raiz, onde está o seu main.py e requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m compileall . 

      - name: Disparar Deploy no Easypanel
        if: github.event_name == 'push' && success()
        run: curl -f -s -S -X POST "${{ secrets.EASYPANEL_WEBHOOK_PYTHON }}"
